_user:
    resource: "@ProjBussinesTripBundle/Controller/UserController.php"
    type:     annotation
_vehicle:
    resource: "@ProjBussinesTripBundle/Controller/VehicleController.php"
    type:     annotation
_trip:
    resource: "@ProjBussinesTripBundle/Controller/TripController.php"
    type:     annotation
_expenses:
    resource: "@ProjBussinesTripBundle/Controller/ExpenseController.php"
    type:     annotation
_tripPoint:
    resource: "@ProjBussinesTripBundle/Controller/TripPointController.php"
    type:     annotation
_report:
    resource: "@ProjBussinesTripBundle/Controller/ReportController.php"
    type:     annotation