_user:
    resource: "@ProjBussinesTripBundle/Controller/UserController.php"
    type:     annotation
_vehicle:
    resource: "@ProjBussinesTripBundle/Controller/VehicleController.php"
    type:     annotation
_trip:
    resource: "@ProjBussinesTripBundle/Controller/TripController.php"
    type:     annotation