imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: assetic.php }
    - { resource: services.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig', 'php']
    #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        #handler_id:     session.handler.memcached
        cookie_lifetime: 86400
        gc_maxlifetime: 1800
        gc_probability: 1
        gc_divisor: 1
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   "%database_driver%"
                host:     "%database_host%"
                dbname:   "%database_name%"
                port:     "%database_port%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8
    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: ~
                mappings:
                    ProjBaseBundle: ~
                    JMoseCommandSchedulerBundle: ~
                dql:
                    numeric_functions:
                        isnull: Proj\Base\Dql\IsNull
                        isequal: Proj\Base\Dql\IsEqual
                        bitnot: Proj\Base\Dql\BitNot

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
