root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /main
        permanent: true

_proj_base:
    resource: "@ProjBaseBundle/Resources/config/routing.yml"
