security:
    encoders:
        Proj\Base\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_DEVELOPER: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        users:
            entity:
                class: ProjBaseBundle:User
                property: login
                manager_name: default
    firewalls:
        login_firewall:
            pattern:   .*
            anonymous: ~
#        logged:
#            pattern: .*
#            switch_user: { role: ROLE_ALLOWED_TO_SWITCH, parameter: _switch_to }
#            form_login:
#                always_use_default_target_path: true
#                default_target_path: /main
#                success_handler: proj.auth.success
#            logout:
#                target: /main

    access_control:
        #- { path: ^/switch, requires_channel: https, allow_if: 'user.can(1)' } # 1 -> Permission::DEV_TOOLS