security:
    encoders:
        Proj\Base\Entity\User:
            algorithm: sha1
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ACCOUNTANT: ROLE_USER
        ROLE_ADMIN: [ROLE_USER, ROLE_ACCOUNTANT, ROLE_ALLOWED_TO_SWITCH]
    providers:
        users:
            entity:
                class: ProjBaseBundle:User
                property: email
                manager_name: default
    firewalls:
        login_firewall:
            pattern:   ^/login$
            anonymous: ~
        logged:
            pattern: .*
            simple_form:
                authenticator: proj.auth.autenticator
                check_path:    /login_check
                login_path:    /login
                always_use_default_target_path: true
                default_target_path: /trip/index
                success_handler: proj.auth.success
            logout:
                target: /login

    access_control:
        #- { path: ^/switch, requires_channel: https, allow_if: 'user.can(1)' } # 1 -> Permission::DEV_TOOLS