# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ["@knp_menu.factory"]

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory_service: app.menu_builder
        factory_method: createMainMenu
        arguments: ["@request_stack"]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
    app.datagrid.builder.vehicle_grid:
        class: AppBundle\DataGrid\VehicleGrid
        arguments: ["@thrace_data_grid.factory.datagrid", "@translator", "@router", "@doctrine.orm.entity_manager"]
    app.datagrid.vehicle_grid:
        class: Thrace\DataGridBundle\DataGrid\DataGrid
        factory_service: app.datagrid.builder.vehicle_grid
        factory_method: build
        tags:
            - { name: thrace_data_grid.datagrid, alias: vehicle_grid }
    app.datagrid.event_listener.vehicle_grid_edit:
        class: AppBundle\DataGrid\VehicleGridEdit
        calls:
          - [setContainer, [@service_container]]
        tags:
          - { name: kernel.event_listener, event: thrace_datagrid.onRowAdd, method: onRowAdd }
          - { name: kernel.event_listener, event: thrace_datagrid.onRowEdit, method: onRowEdit }
          - { name: kernel.event_listener, event: thrace_datagrid.onRowDel, method: onRowDelete }
    app.datagrid.builder.trip_grid:
        class: AppBundle\DataGrid\TripGrid
        arguments: ["@thrace_data_grid.factory.datagrid", "@translator", "@router", "@doctrine.orm.entity_manager"]
    app.datagrid.trip_grid:
        class: Thrace\DataGridBundle\DataGrid\DataGrid
        factory_service: app.datagrid.builder.trip_grid
        factory_method: build
        tags:
            - { name: thrace_data_grid.datagrid, alias: trip_grid }