services:
    proj.twig.base_extension:
        class: Proj\Base\Twig\BaseExtension
        tags:
            - { name: twig.extension }
    proj.twig.menu_extension:
        class: Proj\Base\Twig\MenuExtension
        arguments: ["@security.token_storage", "@security.authorization_checker", "@doctrine", "@translator", "@session"]
        tags:
            - { name: twig.extension }
    http.utils.class:
        class: Symfony\Component\Security\Http\HttpUtils
    proj.base.locale_listener:
        class: Proj\Base\EventListener\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    proj.base.js_filter:
        class: Proj\Base\Assetic\Filter\JSFilter
        tags:
            - { name: assetic.filter, alias: js_filter }
#    session.memcached:
#        class: Memcached
#        arguments:
#            persistent_id: %session_memcached_prefix%
#        calls:
#            - [ addServer, [ %session_memcached_host%, %session_memcached_port% ]]
#    session.handler.memcached:
#        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\MemcachedSessionHandler
#        arguments: [@session.memcached, { prefix: %session_memcached_prefix%, expiretime: %session_memcached_expire% }]
    proj.auth.success:
        class: Proj\Base\Service\AuthenticationSuccessHandler
        arguments: ["@http.utils.class", "@doctrine"]
        services:
    proj.auth.autenticator:
        class: Proj\Base\Security\ImapAuthenticator
        arguments: ["@security.password_encoder", "@doctrine"]