login:
    path: /login
    defaults: { _controller: ProjBaseBundle:Security:index }
login_check:
    path: /login_check
    defaults: { _controller: ProjBaseBundle:Security:index }
logout:
    path: /logout

_form:
    resource: "@ProjBaseBundle/Controller/FormController.php"
    type:     annotation